# Generated by Django 5.2.3 on 2025-07-04 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Клик по кнопке',
                'verbose_name_plural': 'Клики по кнопкам',
                'db_table': 'button_clicks',
                'ordering': ('-ts',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Ключ')),
                ('text', models.TextField(blank=True, verbose_name='Контент')),
                ('media_kind', models.CharField(choices=[('NONE', 'Нет'), ('PHOTO', 'Фото'), ('VIDEO', 'Видео')], default='NONE', max_length=5, verbose_name='Медиа')),
                ('media_url', models.URLField(blank=True, verbose_name='URL медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Редактор',
                'verbose_name_plural': 'Редактор',
                'db_table': 'contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('media_kind', models.CharField(choices=[('NONE', 'Нет'), ('PHOTO', 'Фото'), ('VIDEO', 'Видео')], default='NONE', max_length=5, verbose_name='Медиа')),
                ('media_url', models.URLField(blank=True, verbose_name='URL медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'mailings',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailingSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=7, verbose_name='Статус')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Отправка рассылки',
                'verbose_name_plural': 'Отправки рассылок',
                'db_table': 'mailing_sends',
                'ordering': ('-ts',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('MARKETBEAT', 'Ежеквартальный отчет MARKETBEAT'), ('SEGMENT', 'Обзоры по сегментам рынка'), ('ANALYTICS', 'Услуги компании')], max_length=10, verbose_name='Раздел')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('label', models.CharField(max_length=120, verbose_name='Текст кнопки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('media_kind', models.CharField(choices=[('NONE', 'Нет'), ('PHOTO', 'Фото'), ('VIDEO', 'Видео')], default='NONE', max_length=5, verbose_name='Медиа')),
                ('media_url', models.URLField(blank=True, verbose_name='URL медиа')),
                ('payload', models.TextField(blank=True, help_text='Для MARKETBEAT — URL отчёта; для консультации — текст ответа', verbose_name='Ссылка или текст сообщения')),
                ('callback', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'db_table': 'menu_buttons',
                'ordering': ('section', 'order'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(editable=False, unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
