"""add parent_id to MenuButton

Revision ID: 44ec58bbb961
Revises: 11bfcf409ff8
Create Date: 2025-07-14 11:39:51.682965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ec58bbb961'
down_revision: Union[str, Sequence[str], None] = '11bfcf409ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_buttons', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'menu_buttons', 'menu_buttons', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_buttons', type_='foreignkey')
    op.drop_column('menu_buttons', 'parent_id')
    # ### end Alembic commands ###
